disabled_rules:
- type_body_length
- line_length
- type_name
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
